### ISSUE TITLE
4 spaces over 2

### ISSUE THREAD

**Issue by kyleshrives** [gathercontent/javascript#1]
@magalhini 

We currently apply 4 spaces (before adding the linting rule) but the Airbnb standard assumes we should stick with 2. I personally struggle with how close 2 spaces are.

**Examples**

- 2 space: https://cl.ly/3H1v0h0F0y1T 
- 4 space: https://cl.ly/3M270o0a3M0P

I can get use to it but I was just wondering what your thoughts were on this?

**Comment by magalhini** [comment]
Given the setup that I use, I'm becoming more and more a fan of 2 spaces. It's easier on 2 column/split view on any Editor and especially with JSX, I'm preferring it the more I use it and see it.

However, as I've mentioned to you before, I have absolutely no problem with 4 spaces as well. So maybe it would be interesting to hear about everyone else's opinions on this too and see what they think?

**Comment by kyleshrives** [comment]
I'm inclined to move over to 2 spaces. If you & the Airbnb standard suggest 2 spaces then lets go to that and review it at a later date.

Any change looks strange to begin with but it'll become the norm soon enough 👍
